### Hello

GET http://localhost:3000

### Post Create Task

POST http://localhost:3000/task
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RlIiwic3ViIjoiOTFhOWE1YTUtNDI5ZC00ZWViLTkzMDgtZjczNzFjYTNlMzhlIiwiaWF0IjoxNzI0NjQ4NDYyLCJleHAiOjE3MjQ2NTIwNjJ9.5UFnYtxrJcOLXpphImd3sMI9_SHl-9vL2IbWF9M4xE0

{
  "title": "1awdnlajldlasnlna21awdnlajldlasnlna21awdnlajldlasnlna2",
  "description": "description",
  "expirationDate": "2024-08-25"
}

###

POST http://localhost:3000/task
Content-Type: application/json

{
  "id": "111112222",
  "title": "oto",
  "description": "description",
  "status": "desc oto",
  "expirationDate": "2024-08-25"
}

### Get Task by id

GET http://localhost:3000/task/37f0a057-81a2-4d22-ae07-43b2ce2721be
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RlIiwic3ViIjoiOTFhOWE1YTUtNDI5ZC00ZWViLTkzMDgtZjczNzFjYTNlMzhlIiwiaWF0IjoxNzI0NjQ4NDYyLCJleHAiOjE3MjQ2NTIwNjJ9.5UFnYtxrJcOLXpphImd3sMI9_SHl-9vL2IbWF9M4xE0

### Update Task by id

PUT http://localhost:3000/task/37f0a057-81a2-4d22-ae07-43b2ce2721be
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RlIiwic3ViIjoiOTFhOWE1YTUtNDI5ZC00ZWViLTkzMDgtZjczNzFjYTNlMzhlIiwiaWF0IjoxNzI0NjQ4NDYyLCJleHAiOjE3MjQ2NTIwNjJ9.5UFnYtxrJcOLXpphImd3sMI9_SHl-9vL2IbWF9M4xE0

{
  "title": "new title",
  "description": "new description",
  "status": "DONE",
  "expirationDate": "2024-08-25"
}

### Delete task

DELETE http://localhost:3000/task/37f0a057-81a2-4d22-ae07-43b2ce2721be
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RlIiwic3ViIjoiOTFhOWE1YTUtNDI5ZC00ZWViLTkzMDgtZjczNzFjYTNlMzhlIiwiaWF0IjoxNzI0NjQ4NDYyLCJleHAiOjE3MjQ2NTIwNjJ9.5UFnYtxrJcOLXpphImd3sMI9_SHl-9vL2IbWF9M4xE0

### Find by parameters

GET http://localhost:3000/task?title=1awdnlaj
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RlIiwic3ViIjoiOTFhOWE1YTUtNDI5ZC00ZWViLTkzMDgtZjczNzFjYTNlMzhlIiwiaWF0IjoxNzI0NjQ4NDYyLCJleHAiOjE3MjQ2NTIwNjJ9.5UFnYtxrJcOLXpphImd3sMI9_SHl-9vL2IbWF9M4xE0

###
GET http://localhost:3000/task?status=DO
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RlIiwic3ViIjoiOTFhOWE1YTUtNDI5ZC00ZWViLTkzMDgtZjczNzFjYTNlMzhlIiwiaWF0IjoxNzI0NjQ4NDYyLCJleHAiOjE3MjQ2NTIwNjJ9.5UFnYtxrJcOLXpphImd3sMI9_SHl-9vL2IbWF9M4xE0

###

GET http://localhost:3000/task
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RlIiwic3ViIjoiOTFhOWE1YTUtNDI5ZC00ZWViLTkzMDgtZjczNzFjYTNlMzhlIiwiaWF0IjoxNzI0NjQ4NDYyLCJleHAiOjE3MjQ2NTIwNjJ9.5UFnYtxrJcOLXpphImd3sMI9_SHl-9vL2IbWF9M4xE0

###
GET http://localhost:3000/task?status=status&title=title
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RlIiwic3ViIjoiOTFhOWE1YTUtNDI5ZC00ZWViLTkzMDgtZjczNzFjYTNlMzhlIiwiaWF0IjoxNzI0NjQ4NDYyLCJleHAiOjE3MjQ2NTIwNjJ9.5UFnYtxrJcOLXpphImd3sMI9_SHl-9vL2IbWF9M4xE0

### Create User

POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "teste",
  "password": "12345"
}

### Auth/login

POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "teste",
  "password": "12345"
}
