### Hello

GET http://localhost:3000

### Post Create Task

POST http://localhost:3000/task
Content-Type: application/json

{
  "id": "asdkjbackjsbaj",
  "title": "title",
  "description": "description",
  "status": "status",
  "expirationDate": "2024-08-25"
}

###

POST http://localhost:3000/task
Content-Type: application/json

{
  "id": "111112222",
  "title": "oto",
  "description": "description",
  "status": "desc oto",
  "expirationDate": "2024-08-25"
}

### Get Task by id

GET http://localhost:3000/task/asdkjbackjsbaj

### Update Task by id

PUT http://localhost:3000/task/asdkjbackjsbaj
Content-Type: application/json

{
  "title": "new title",
  "description": "new description",
  "status": "new status",
  "expirationDate": "2024-08-25"
}

### Delete task

DELETE http://localhost:3000/task/asdkjbackjsbaj

### Find by parameters

GET http://localhost:3000/task?title=title

###
GET http://localhost:3000/task?status=oto

###

GET http://localhost:3000/task

###
GET http://localhost:3000/task?status=status&title=title

### Create User

POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "teste",
  "password": "12345"
}

### Auth/login

POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "teste",
  "password": "12345"
}
